import type { Metadata } from "next";
import { Inter,IBM_Plex_Serif } from "next/font/google"
import "./globals.css";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import Providers from "@/context/Providers";
import { ourFileRouter } from "./api/uploadthing/core";


// const inter = Inter({ subsets: ["latin"] });
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });
// const ibmPlexSerif = IBM_Plex_Serif({ subsets: ["latin"], weight: ['400', '700'], variable: '--font-ibm-plex-serif' });


export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      
      <NextSSRPlugin
          
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
     
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        
        <Providers>  {children}</Providers>

</body>
    </html>
  );
}
